server:
  port: 8001
  servlet:
    context-path: /catalogs/

spring:
  data:
    mongodb:
      database: catalog
      port: 27017

      auto-index-creation: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

message: Hello from Catalog Server

management:
  endpoints:
    web:
      exposure:
        include: '*'
